/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CarRental;
import Business.WorkQueue.CarRentalWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import Business.Car;
import java.text.SimpleDateFormat;
import javax.swing.JPanel;
import java.util.Date;
import java.text.DateFormat;
/**
 *
 * @author Oliver
 */
public class ApproveRentalJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    CarRentalWorkRequest request;
    Car myCar;
    /**
     * Creates new form ApproveRentalJPanel
     */
    public ApproveRentalJPanel(JPanel userProcessContainer, CarRentalWorkRequest request, Car myCar) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.myCar = myCar;
        if (request.getIsCancellation()){
            labelIsCancel.setText("Yes");
        }
        else{
            labelIsCancel.setText("No");
        }
        
        DateFormat dateFormat = new SimpleDateFormat("yyyyMMdd");
        
        Date curDate = new Date();
        
        int age = (Integer.parseInt(dateFormat.format(curDate)) - Integer.parseInt(request.getSender().getDob()))/10000;
        
        if (request.getIsCredits()){
            labelIsCredits.setText("Yes");
            //labelOriginalPrice.setText(Double.toString(request.getSender().getCustomerOrder().get(request.getRow()).getPrice()));
            btnGenNewPrice.setEnabled(true);
        }
        else{
            btnGenNewPrice.setEnabled(false);
            labelIsCredits.setText("No");
        }
        labelCredits.setText(Double.toString(request.getSender().getCredits()));
        if (request.getSender().getDriverLicense().trim() != ""){
            labelDL.setText(request.getSender().getDriverLicense());
        }
        else{
            labelDL.setText("No driver license in record");
        }
        
        labelAge.setText(Integer.toString(age));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnDecline = new javax.swing.JButton();
        txtDeclineMsg = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        labelIsCancel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        labelAge = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelDL = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        labelCredits = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelIsCredits = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        labelNewPrice = new javax.swing.JLabel();
        btnGenNewPrice = new javax.swing.JButton();
        btnApprove = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        backJButton.setText("<<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel1.setText("Manage Rental Request");

        btnDecline.setText("Decline request");
        btnDecline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeclineActionPerformed(evt);
            }
        });

        txtDeclineMsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeclineMsgActionPerformed(evt);
            }
        });

        jLabel5.setText("Decline reason");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cancellation"));

        jLabel6.setText("A cancellation request?");

        labelIsCancel.setText("Yes/No");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(labelIsCancel)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(labelIsCancel))
                .addGap(18, 18, 18))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Regular application info"));

        jLabel7.setText("Customer's age: ");

        labelAge.setText("Display age");

        jLabel8.setText("Customer's Driver License: ");

        labelDL.setText("Dsiplay DL");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(labelDL))
                    .addComponent(jLabel7)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(labelAge)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(labelAge))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(labelDL))
                .addGap(18, 18, 18))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Discount application"));

        jLabel10.setText("Customer's Credits: ");

        labelCredits.setText("Display Credits");

        jLabel4.setText("New Price: ");

        labelIsCredits.setText("Yes/No");

        jLabel11.setText("Using credits?");

        btnGenNewPrice.setText("Generate New Price");
        btnGenNewPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenNewPriceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(labelIsCredits)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(labelCredits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(26, 26, 26))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(74, 74, 74)
                        .addComponent(labelNewPrice)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnGenNewPrice)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIsCredits)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(labelCredits))
                .addGap(18, 18, 18)
                .addComponent(btnGenNewPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(labelNewPrice))
                .addContainerGap())
        );

        btnApprove.setText("Approve request");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/AdministrativeRole/xitong.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Airliner/jifen.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Airliner/denglu.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Airliner/quxiao.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(backJButton)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel9)
                                .addComponent(jLabel2))
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(51, 51, 51)
                                    .addComponent(txtDeclineMsg))
                                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btnApprove)
                        .addGap(18, 18, 18)
                        .addComponent(btnDecline)))
                .addContainerGap(288, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(backJButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDeclineMsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDecline)
                            .addComponent(btnApprove))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CarRentalWorkAreaJPanel carRentalWorkAreaJP = (CarRentalWorkAreaJPanel) component;
        carRentalWorkAreaJP.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void txtDeclineMsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeclineMsgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeclineMsgActionPerformed

    private void btnDeclineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeclineActionPerformed
        // TODO add your handling code here:
        if (txtDeclineMsg.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please return an explanation for declined request!", "Warning", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (request.getIsCancellation()){
            request.getSender().getWorkQueue().getRequestMap().get("CarRental").get(request.getRow()).setStatus("Cancellation Declined");
            request.setStatus("Completed");
            request.getSender().getCustomerOrder().get(request.getRow()).setIsAvailable(false);
            request.getSender().getWorkQueue().getRequestMap().get("CarRental").get(request.getRow()).setMessage(txtDeclineMsg.getText());
        }
        else{
            //if rent being declined, there's no such order in customerOrder
            request.setStatus("Declined");
            for (Car car : request.getReceiver().getCarCatalog()){
                if (car.getCarID()==(myCar.getCarID())){
                    car.setIsAvailable(true);
                }
            }
            int cnt = 0;
            for (Car car : request.getSender().getCustomerOrder()){
                if ((car.getCompanyName().equals(myCar.getCompanyName()))&&(car.getCarID()==myCar.getCarID())){
                    break;
                }
                cnt++;
            }
            request.getSender().getCustomerOrder().remove(cnt);
            request.getSender().getWorkQueue().getRequestMap().get("CarRental").remove(cnt);
            
        }
        System.out.println("OrderHistory: order size: " + request.getSender().getCustomerOrder().size() + ", car request size" + request.getSender().getWorkQueue().getRequestMap().get("CarRental").size());
        request.setMessage(txtDeclineMsg.getText());
        
        JOptionPane.showMessageDialog(null, "Action has been done to this request!", "Warning", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnDeclineActionPerformed

    private void btnGenNewPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenNewPriceActionPerformed
        // TODO add your handling code here:
        
        Double newPrice = myCar.getPrice() - Double.parseDouble(labelCredits.getText());
        labelNewPrice.setText(Double.toString(newPrice));
        
        
        
    }//GEN-LAST:event_btnGenNewPriceActionPerformed

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        String newPrice = "";
        if (request.getIsCancellation()){
            
            request.getSender().getCustomerOrder().get(request.getRow()).setIsAvailable(true);
            System.out.println("approve panel: " + request.getPrice());
            if (request.getSender().getCredits()-request.getPrice()/10.0 >= 0.0){
                request.getSender().addCredits(0-request.getPrice()/10.0);
            }
            request.getSender().getCustomerOrder().remove(request.getRow());
            //System.out.println("???????  " + request.getRow());
            //System.out.println("before: " + request.getSender().getWorkQueue().getWorkRequestList().size());
            //request.getSender().getWorkQueue().getWorkRequestList().remove(request.getSender().getWorkQueue().getWorkRequestList().size()-1);
            request.getSender().getWorkQueue().getRequestMap().get("CarRental").remove(request.getRow());
            System.out.println("Approve panel: orderhistory" + request.getSender().getCustomerOrder().size() + ", request row: " + request.getRow());
            
            //System.out.println("after: " + request.getSender().getWorkQueue().getWorkRequestList().size());
        }
        //        else if ((String)comboClass.getSelectedItem()!="" && txtNewPrice.getText() != ""){
            //            request.setNewClass((String)comboClass.getSelectedItem());
            //            request.setNewPrice(Double.parseDouble(txtNewPrice.getText()));
            //
            //        }

        else{
            if (labelDL.getText().trim().equals("")){
                JOptionPane.showMessageDialog(null, "Can't approve rentals without driver license", "Warning", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            
            if (request.getIsCredits()){
                System.out.println(labelNewPrice.getText());
                if (labelNewPrice.getText().trim().equals("")){
                    JOptionPane.showMessageDialog(null, "Please check the new price with customer credits included!", "Warning", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
                for (Car car : request.getReceiver().getCarCatalog()){
                    if (car.getCarID()==(myCar.getCarID())){
                        car.setIsAvailable(false);
                    }
                }
                request.getSender().addCredits(Double.parseDouble(labelNewPrice.getText())/10.0);
                request.setPriceChange(true);
                request.setPrice(Double.parseDouble(labelNewPrice.getText()));
                
            }
            else{
                request.getSender().addCredits(myCar.getPrice()/10.0);
                for (Car car : request.getReceiver().getCarCatalog()){
                    if (car.getCarID()==(myCar.getCarID())){
                        car.setIsAvailable(false);
                    }
                }
            }
            
            //System.out.println(request.getSender().getCustomerOrder().get(request.getRow()).getIsAvailable());
        }
        
        request.setStatus("Completed");
        request.setMessage("Request approved");
        JOptionPane.showMessageDialog(null, "Action has been done to this request!", "Warning", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnApproveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnDecline;
    private javax.swing.JButton btnGenNewPrice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelAge;
    private javax.swing.JLabel labelCredits;
    private javax.swing.JLabel labelDL;
    private javax.swing.JLabel labelIsCancel;
    private javax.swing.JLabel labelIsCredits;
    private javax.swing.JLabel labelNewPrice;
    private javax.swing.JTextField txtDeclineMsg;
    // End of variables declaration//GEN-END:variables
}
