/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RailWay;

import Business.RailWay;
import Business.WorkQueue.RailWayWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author chenweikai
 */
public class ApproveBookingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ApproveBookingJPanel
     */
    JPanel userProcessContainer;
    RailWayWorkRequest request;
    RailWay myRailway;
    public ApproveBookingJPanel(JPanel userProcessContainer,RailWayWorkRequest request, RailWay myRailway) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.myRailway = myRailway;
        if (request.getIsCancellation()){
            labelIsCancel9.setText("Yes");
        }
        else{
            labelIsCancel9.setText("No");
        }
        if (request.getIsCredits()){
            labelIsCredits8.setText("Yes");
            //labelOriginalPrice.setText(Double.toString(request.getSender().getCustomerBooking().get(request.getRow()).getPrice()));
            btnGenNewPrice8.setEnabled(true);
        }
        else{
            btnGenNewPrice8.setEnabled(false);
            labelIsCredits8.setText("No");
        }
        
        labelCredits8.setText(Double.toString(request.getSender().getCredits()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboRoom1 = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        btnDecline = new javax.swing.JButton();
        btnApprove = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        comboRoom2 = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        txtDeclineMsg1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelIsCancel1 = new javax.swing.JLabel();
        btnDeclineRoom = new javax.swing.JButton();
        btnApproveRoom = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        labelCredits8 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        labelIsCredits8 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        labelNewPrice8 = new javax.swing.JLabel();
        btnGenNewPrice8 = new javax.swing.JButton();
        txtDeclineMsg9 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        labelIsCancel9 = new javax.swing.JLabel();
        labelNewPrice9 = new javax.swing.JLabel();
        comboExtraSeat = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();

        comboRoom1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Small", "Medium", "Large" }));
        comboRoom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRoom1ActionPerformed(evt);
            }
        });

        jLabel13.setText("Room Type");

        btnDecline.setText("Decline Seat request");
        btnDecline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeclineActionPerformed(evt);
            }
        });

        btnApprove.setText("Approve Seat request");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });

        backJButton.setText("<<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Approve Room Request"));
        jPanel2.setToolTipText("");

        comboRoom2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Small", "Medium", "Large" }));
        comboRoom2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRoom2ActionPerformed(evt);
            }
        });

        jLabel14.setText("Change Balcony Type");

        txtDeclineMsg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeclineMsg1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Decline reason");

        jLabel8.setText("A Cancellation Request:");

        labelIsCancel1.setText("Yes/No");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboRoom2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDeclineMsg1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(labelIsCancel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(comboRoom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDeclineMsg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(labelIsCancel1))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        btnDeclineRoom.setText("Decline Balcony request");
        btnDeclineRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeclineRoomActionPerformed(evt);
            }
        });

        btnApproveRoom.setText("Approve Balcony request");
        btnApproveRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveRoomActionPerformed(evt);
            }
        });

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Discount application"));

        jLabel52.setText("Customer's Credits: ");

        labelCredits8.setText("Display Credits");

        jLabel53.setText("New Price: ");

        labelIsCredits8.setText("Yes/No");

        jLabel54.setText("Using credits?");

        btnGenNewPrice8.setText("Generate New Price");
        btnGenNewPrice8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenNewPrice8ActionPerformed(evt);
            }
        });

        txtDeclineMsg9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeclineMsg9ActionPerformed(evt);
            }
        });

        jLabel48.setText("Decline reason");

        jLabel49.setText("A cancellation request?");

        labelIsCancel9.setText("Yes/No");

        comboExtraSeat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yes", "No"}));
        comboExtraSeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboExtraSeatActionPerformed(evt);
            }
        });

        jLabel10.setText("Extra Seat");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(btnGenNewPrice8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelNewPrice8))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel49)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel52)
                            .addComponent(jLabel54))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(labelIsCredits8)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                                .addGap(0, 94, Short.MAX_VALUE)
                                .addComponent(labelCredits8, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel48)
                        .addGap(165, 165, 165)
                        .addComponent(txtDeclineMsg9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboExtraSeat, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel53)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelIsCancel9)
                            .addComponent(labelNewPrice9, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIsCredits8)
                    .addComponent(jLabel54))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel52)
                    .addComponent(labelCredits8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(comboExtraSeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(labelNewPrice8)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGenNewPrice8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel53)
                    .addComponent(labelNewPrice9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(labelIsCancel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDeclineMsg9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel48))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDecline)
                            .addComponent(btnApprove)
                            .addComponent(btnDeclineRoom)
                            .addComponent(btnApproveRoom)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(backJButton)))
                .addGap(0, 204, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(221, Short.MAX_VALUE)
                .addComponent(btnApprove)
                .addGap(39, 39, 39)
                .addComponent(btnDecline)
                .addGap(175, 175, 175)
                .addComponent(btnApproveRoom)
                .addGap(36, 36, 36)
                .addComponent(btnDeclineRoom)
                .addGap(205, 205, 205))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(backJButton)
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeclineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeclineActionPerformed
        // TODO add your handling code here:
        
        
         if (txtDeclineMsg9.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please return an explanation for declined request!", "Warning", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (request.getIsCancellation()){
            request.getSender().getWorkQueue().getRequestMap().get("Hotel").get(request.getRow()).setStatus("Cancellation Declined");
            request.setStatus("Completed");
            double m = request.getSender().getCustomerRailWayBooking().get(request.getRow()).getSeatAvail() + 1;
            request.getSender().getCustomerRailWayBooking().get(request.getRow()).setSeatAvail(m);

//request.getSender().getCustomerRailWayBooking().get(request.getRow()).setIsAvailable(false);
            request.getSender().getWorkQueue().getRequestMap().get("Hotel").get(request.getRow()).setMessage(txtDeclineMsg9.getText());
        }
        else{
            //if rent being declined, there's no such order in customerRailWayBooking
            request.setStatus("Declined");
            for (RailWay railway : request.getReceiver().getRailwayCatalog()){
                if (railway.getRailwayid()==(myRailway.getRailwayid())){
                    railway.setIsAvailable(true);
                    double m =railway.getSeatAvail() + 1;
                   railway.setSeatAvail(m);
                }
            }
            int cnt = 0;
            for (RailWay railway : request.getSender().getCustomerRailWayBooking()){
                if ((railway.getCompanyName().equals(myRailway.getCompanyName()))&&(railway.getRailwayid()==myRailway.getRailwayid())){
                    break;
                }
                cnt++;
            }
            request.getSender().getCustomerRailWayBooking().remove(cnt);
            request.getSender().getWorkQueue().getRequestMap().get("RailWay").remove(cnt);
            
        }
        System.out.println("OrderHistory: order size: " + request.getSender().getCustomerRailWayBooking().size() + ", Hotel request size" + request.getSender().getWorkQueue().getRequestMap().get("RailWay").size());
        request.setMessage(txtDeclineMsg9.getText());
        
        JOptionPane.showMessageDialog(null, "Action has been done to this request!", "Warning", JOptionPane.INFORMATION_MESSAGE);
                                                  

   
    }//GEN-LAST:event_btnDeclineActionPerformed

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        String extra = (String)comboExtraSeat.getSelectedItem();
        if(extra == "Yes"){
            double m = request.getSender().getCustomerRailWayBooking().get(request.getRow()).getSeatAvail() - 1;
            request.getSender().getCustomerRailWayBooking().get(request.getRow()).setSeatAvail(m);
        }
        else{
            double m = request.getSender().getCustomerRailWayBooking().get(request.getRow()).getSeatAvail();
            request.getSender().getCustomerRailWayBooking().get(request.getRow()).setSeatAvail(m);
        }
        
        String newPrice = "";
        if (request.getIsCancellation()){
            
            request.getSender().getCustomerRailWayBooking().get(request.getRow()).setIsAvailable(true);
            System.out.println("approve panel: " + request.getPrice());
            if (request.getSender().getCredits()-request.getPrice()/10.0 >= 0.0){
                request.getSender().addCredits(0-request.getPrice()/10.0);
            }
            request.getSender().getCustomerRailWayBooking().remove(request.getRow());
            //System.out.println("???????  " + request.getRow());
            //System.out.println("before: " + request.getSender().getWorkQueue().getWorkRequestList().size());
            //request.getSender().getWorkQueue().getWorkRequestList().remove(request.getSender().getWorkQueue().getWorkRequestList().size()-1);
            request.getSender().getWorkQueue().getRequestMap().get("RailWay").remove(request.getRow());
            System.out.println("Approve panel: orderhistory" + request.getSender().getCustomerRailWayBooking().size() + ", request row: " + request.getRow());
            
            //System.out.println("after: " + request.getSender().getWorkQueue().getWorkRequestList().size());
        }
        //        else if ((String)comboClass.getSelectedItem()!="" && txtNewPrice.getText() != ""){
            //            request.setNewClass((String)comboClass.getSelectedItem());
            //            request.setNewPrice(Double.parseDouble(txtNewPrice.getText()));
            //
            //        }

        else{
            
            
            if (request.getIsCredits()){
                System.out.println(labelNewPrice9.getText());
                if (labelNewPrice9.getText().trim().equals("")){
                    JOptionPane.showMessageDialog(null, "Please check the new price with customer credits included!", "Warning", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
                for (RailWay railway : request.getReceiver().getRailwayCatalog()){
                    if (railway.getRailwayid()==(myRailway.getRailwayid())){
                        railway.setIsAvailable(false);
                    }
                }
                request.getSender().addCredits(Double.parseDouble(labelNewPrice9.getText())/10.0);
                request.setPriceChange(true);
                request.setPrice(Double.parseDouble(labelNewPrice9.getText()));
                
            }
            else{
                request.getSender().addCredits(myRailway.getPrice()/10.0);
                for (RailWay railway : request.getReceiver().getRailwayCatalog()){
                    if (railway.getRailwayid()==(myRailway.getRailwayid())){
                        railway.setIsAvailable(false);
                    }
                }
            }
            
            //System.out.println(request.getSender().getCustomerBooking().get(request.getRow()).getIsAvailable());
        }
        
        request.setStatus("Completed");
        request.setMessage("Request approved");
        JOptionPane.showMessageDialog(null, "Action has been done to this request!", "Warning", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnApproveActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        RailWayWorkAreaJPanel railwayWorkAreaJP = (RailWayWorkAreaJPanel) component;
        railwayWorkAreaJP.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void comboRoom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRoom1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboRoom1ActionPerformed

    private void comboRoom2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRoom2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboRoom2ActionPerformed

    private void txtDeclineMsg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeclineMsg1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeclineMsg1ActionPerformed

    private void btnDeclineRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeclineRoomActionPerformed
        // TODO add your handling code here:
        double m = request.getSender().getCustomerRailWayBooking().get(request.getRow()).getRoomAvail() + 1;
        request.getSender().getCustomerRailWayBooking().get(request.getRow()).setRoomAvail(m);
        
        if (txtDeclineMsg1.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please return an explanation for declined request!", "Warning", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (request.getIsCancellation()){
            request.setStatus("Completed");
            request.getSender().getCustomerRailWayBooking().get(request.getRow()).setIsAvailable(false);
        }
        else{
            //if rent being declined, there's no such order in customerOrder
            request.setStatus("Declined");
            request.getSender().getCustomerRailWayBooking().get(request.getRow()).setIsAvailable(true);
            request.getSender().getCustomerRailWayBooking().remove(request.getRow());
            request.getSender().getWorkQueue().getWorkRequestList().remove(request.getRow());

        }
          
        request.setMessage(txtDeclineMsg1.getText());
        JOptionPane.showMessageDialog(null, "Action has been done to this request!", "Warning", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnDeclineRoomActionPerformed

    private void btnApproveRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveRoomActionPerformed
        // TODO add your handling code here:
        //String newPrice = "";
        if (request.getIsCancellation()){
            request.getSender().getCustomerRailWayBooking().get(request.getRow()).setIsAvailable(true);
            request.getSender().getCustomerRailWayBooking().remove(request.getRow());
            //System.out.println("???????  " + request.getRow());
            //System.out.println("before: " + request.getSender().getWorkQueue().getWorkRequestList().size());
            //request.getSender().getWorkQueue().getWorkRequestList().remove(request.getSender().getWorkQueue().getWorkRequestList().size()-1);
            request.getSender().getWorkQueue().getWorkRequestList().remove(request.getRow());

            //System.out.println("after: " + request.getSender().getWorkQueue().getWorkRequestList().size());
        }
        //        else if ((String)comboClass.getSelectedItem()!="" && txtNewPrice.getText() != ""){
            //            request.setNewClass((String)comboClass.getSelectedItem());
            //            request.setNewPrice(Double.parseDouble(txtNewPrice.getText()));
            //
            //        }

        else{
            if ((String)comboRoom2.getSelectedItem()!=""){
                request.setNewClass((String)comboRoom2.getSelectedItem());

            };

            request.getSender().getCustomerRailWayBooking().get(request.getRow()).setIsAvailable(false);
        }

        request.setStatus("Completed");
        request.setMessage("Request approved");
        JOptionPane.showMessageDialog(null, "Action has been done to this request!", "Warning", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnApproveRoomActionPerformed

    private void txtDeclineMsg9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeclineMsg9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeclineMsg9ActionPerformed

    private void btnGenNewPrice8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenNewPrice8ActionPerformed
        // TODO add your handling code here:

        if( myRailway.getPrice() - Double.parseDouble(labelCredits8.getText()) <= 0){
            labelNewPrice9.setText("0");
            return;
        }
        
        String extra = (String)comboExtraSeat.getSelectedItem();
        if(extra == "Yes"){
            Double newPrice = myRailway.getPrice() - Double.parseDouble(labelCredits8.getText()) + (0.8*myRailway.getPrice());
            if( newPrice >= 0){
                labelNewPrice9.setText(Double.toString(newPrice));
           
           }
            else{
                labelNewPrice9.setText("0");
                 return;
            }
          
              }
         if(extra == "No"){
           Double newPrice = myRailway.getPrice() - Double.parseDouble(labelCredits8.getText());
           if( newPrice >= 0){  //Double newPrice = myRailway.getPrice() - Double.parseDouble(labelCredits8.getText()) + (0.8*myRailway.getPrice());
           labelNewPrice9.setText(Double.toString(newPrice));
            }
            else{
                labelNewPrice9.setText("0");
                 return;
            }
        }
    }//GEN-LAST:event_btnGenNewPrice8ActionPerformed

    private void comboExtraSeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboExtraSeatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboExtraSeatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnApproveRoom;
    private javax.swing.JButton btnDecline;
    private javax.swing.JButton btnDeclineRoom;
    private javax.swing.JButton btnGenNewPrice8;
    private javax.swing.JComboBox comboExtraSeat;
    private javax.swing.JComboBox comboRoom1;
    private javax.swing.JComboBox comboRoom2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelCredits8;
    private javax.swing.JLabel labelIsCancel1;
    private javax.swing.JLabel labelIsCancel9;
    private javax.swing.JLabel labelIsCredits8;
    private javax.swing.JLabel labelNewPrice8;
    private javax.swing.JLabel labelNewPrice9;
    private javax.swing.JTextField txtDeclineMsg1;
    private javax.swing.JTextField txtDeclineMsg9;
    // End of variables declaration//GEN-END:variables
}
