/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RailWay;

import Business.EcoSystem;
import Business.Organization.Organization;
import Business.Organization.RailWayOrganization;
import Business.RailWay;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chenweikai
 */
public class RailWayManageJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RailWayManageJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private RailWayOrganization railwayOrganization; 
    public RailWayManageJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.railwayOrganization = (RailWayOrganization)organization;
        populateTable();
    }
    public void populateTable(){
        int rowCount = viewRailWayTable.getRowCount();
        DefaultTableModel model = (DefaultTableModel)viewRailWayTable.getModel();
        for(int i=rowCount-1;i>=0;i--) {
            model.removeRow(i);
        }
        for(RailWay railway : userAccount.getRailwayCatalog()) {
            Object row[] = new Object[4];
            row[0] = railway;
            row[1] = railway.getRailwayNum();
            row[2] = railway.getDeparture();
            row[3] = railway.getArrival();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deleterailway = new javax.swing.JButton();
        viewrailway = new javax.swing.JButton();
        createrailway = new javax.swing.JButton();
        updaterailway = new javax.swing.JButton();
        viewrailway1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewRailWayTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtSearchid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        deleterailway.setText("Delete RailWay");
        deleterailway.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleterailwayActionPerformed(evt);
            }
        });

        viewrailway.setText("Search");
        viewrailway.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewrailwayActionPerformed(evt);
            }
        });

        createrailway.setText("Create Railway");
        createrailway.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createrailwayActionPerformed(evt);
            }
        });

        updaterailway.setText("Update Hotel");
        updaterailway.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updaterailwayActionPerformed(evt);
            }
        });

        viewrailway1.setText("View RailWay");
        viewrailway1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewrailway1ActionPerformed(evt);
            }
        });

        viewRailWayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "RailWay Id", "RailWay Name", "Departure", "Arrival"
            }
        ));
        viewRailWayTable.setToolTipText("");
        jScrollPane1.setViewportView(viewRailWayTable);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel3.setText("Management");

        backBtn.setText("<<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel4.setText("Search by RailWay ID");

        txtSearchid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchidActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/AdministrativeRole/xitong.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Airliner/order-add.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Airliner/gengxin.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Airliner/chazhao.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backBtn)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(viewrailway1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(deleterailway, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(createrailway, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4)
                                        .addComponent(updaterailway, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtSearchid, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(viewrailway)))))
                        .addGap(0, 164, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(createrailway)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updaterailway)
                            .addComponent(jLabel5))
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSearchid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewrailway)
                            .addComponent(jLabel6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewrailway1)
                    .addComponent(deleterailway))
                .addGap(18, 18, 18)
                .addComponent(backBtn)
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleterailwayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleterailwayActionPerformed
        // TODO add your handling code here:
         int selectedrow = viewRailWayTable.getSelectedRow();
        
        if(selectedrow>=0){
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure to delete??","Warning",selectionButton);
            if(selectionResult == JOptionPane.YES_OPTION){
                RailWay railway = (RailWay)viewRailWayTable.getValueAt(selectedrow, 0);
                userAccount.delRailway(railway);
                populateTable();
        }
        }
        else 
            JOptionPane.showMessageDialog(null,"Please select any row");
    }//GEN-LAST:event_deleterailwayActionPerformed

    private void viewrailwayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewrailwayActionPerformed
        // TODO add your handling code here:
        String railwayid;
        if (txtSearchid.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Error: You must enter a valid string for Car ID", "Warning", JOptionPane.INFORMATION_MESSAGE);
            txtSearchid.setText("");
            return;
        }
        else{
            railwayid = txtSearchid.getText();
        }
        for (RailWay railway : userAccount.getRailwayCatalog()){
            if (Integer.toString(railway.getRailwayid()).equals(railwayid)){
                txtSearchid.setText("");
                ViewRailWayJPanel viewRailWayJPanel = new ViewRailWayJPanel(userProcessContainer, railway);
                userProcessContainer.add("ViewRailWayJPanel", viewRailWayJPanel);
                CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                layout.next(userProcessContainer);
                return;
            }
        }
        JOptionPane.showMessageDialog(null, "No such Hotel is found :(", "Warning", JOptionPane.INFORMATION_MESSAGE);
        txtSearchid.setText("");
    }//GEN-LAST:event_viewrailwayActionPerformed

    private void createrailwayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createrailwayActionPerformed
        // TODO add your handling code here:
        CreateRailWayJPanel createrailwayJPanel = new CreateRailWayJPanel(userProcessContainer, userAccount);
        userProcessContainer.add("CarRentalManageJPanel",createrailwayJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_createrailwayActionPerformed

    private void updaterailwayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updaterailwayActionPerformed
        // TODO add your handling code here:
         int row = viewRailWayTable.getSelectedRow();
        if(row<0) {
             JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        RailWay railway = (RailWay)viewRailWayTable.getValueAt(row, 0);
        UpdateRailWayJPanel updateFlightJPanel = new UpdateRailWayJPanel(userProcessContainer,userAccount, railway);
        userProcessContainer.add("UpdateRailWayJPanel", updateFlightJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_updaterailwayActionPerformed

    private void viewrailway1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewrailway1ActionPerformed
        // TODO add your handling code here:
         int row = viewRailWayTable.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        RailWay hotel = (RailWay)viewRailWayTable.getValueAt(row, 0);
        ViewRailWayJPanel viewCarJPanel = new ViewRailWayJPanel(userProcessContainer, hotel);
        userProcessContainer.add("ViewCarJPanel", viewCarJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewrailway1ActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void txtSearchidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchidActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton createrailway;
    private javax.swing.JButton deleterailway;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtSearchid;
    private javax.swing.JButton updaterailway;
    private javax.swing.JTable viewRailWayTable;
    private javax.swing.JButton viewrailway;
    private javax.swing.JButton viewrailway1;
    // End of variables declaration//GEN-END:variables
}
