/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RailWay;

import Business.RailWay;

import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.InputMismatchException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author chenweikai
 */
public class UpdateRailWayJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateRailWayJPanel
     */
     JPanel userProcessContainer;
    UserAccount useraccount;
    RailWay railway;
    public UpdateRailWayJPanel(JPanel userProcessContainer,UserAccount useraccount,RailWay railway) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.useraccount = useraccount;
        this.railway = railway;
        display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        comboSeatType = new javax.swing.JComboBox();
        txtRailWayNum = new javax.swing.JTextField();
        UpdateRailwayBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDeparture = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        txtSeatAvail = new javax.swing.JTextField();
        txtArrival = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        txtPrice = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comboTime = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        comboSeatType1 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtRoomAvail = new javax.swing.JTextField();
        comboRoom = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        jLabel9.setText("Seat Type");

        comboSeatType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hard Seat", "Soft Seat", "Bed" }));
        comboSeatType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSeatTypeActionPerformed(evt);
            }
        });

        UpdateRailwayBtn.setText("Update RailWay");
        UpdateRailwayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateRailwayBtnActionPerformed(evt);
            }
        });

        jLabel7.setText("Ticket Price");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("UPDATE A RAILWAY");

        jLabel6.setText("Seats Available");

        jLabel8.setText("Date");

        jLabel5.setText("Arrival");

        jLabel4.setText("Departure");

        jLabel3.setText("Time");

        backBtn.setText("<<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("RailWay Number");

        comboTime.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Morning", "Noon", "Afternoon", "Night" }));
        comboTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTimeActionPerformed(evt);
            }
        });

        jLabel10.setText("Seat Type");

        comboSeatType1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hard Seat", "Soft Seat", "Bed" }));
        comboSeatType1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSeatType1ActionPerformed(evt);
            }
        });

        jLabel11.setText("Room Type");

        jLabel12.setText("Room Available");

        txtRoomAvail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoomAvailActionPerformed(evt);
            }
        });

        comboRoom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Small", "Medium", "Large" }));
        comboRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRoomActionPerformed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Airliner/gengxin.png"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/AdministrativeRole/shuzi.png"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/AdministrativeRole/riqi.png"))); // NOI18N

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/AdministrativeRole/riqi.png"))); // NOI18N

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/AdministrativeRole/tielu.png"))); // NOI18N

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/AdministrativeRole/tielu.png"))); // NOI18N

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/AdministrativeRole/zuowei.png"))); // NOI18N

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/AdministrativeRole/shuzi.png"))); // NOI18N

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/CarRental/4qichexinghao.png"))); // NOI18N

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Customer/huiyishi.png"))); // NOI18N

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/AdministrativeRole/meiyuandollar153.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addComponent(backBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UpdateRailwayBtn))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtRoomAvail))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(63, 63, 63)
                                        .addComponent(comboRoom, 0, 244, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtDate)
                                            .addComponent(txtDeparture)
                                            .addComponent(txtArrival)
                                            .addComponent(txtSeatAvail)
                                            .addComponent(txtRailWayNum)
                                            .addComponent(comboTime, 0, 244, Short.MAX_VALUE)
                                            .addComponent(comboSeatType1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(36, 36, 36)
                                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(332, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel1))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRailWayNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtArrival, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(comboSeatType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSeatAvail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel21)
                    .addComponent(comboRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtRoomAvail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(UpdateRailwayBtn))
                .addGap(67, 67, 67))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public void display(){
        txtRailWayNum.setText(railway.getRailwayNum());
        txtDate.setText(railway.getDate());
        txtPrice.setText(Double.toString(railway.getPrice()));
        txtSeatAvail.setText(Double.toString(railway.getSeatAvail()));
        txtDeparture.setText(railway.getDeparture());
        txtArrival.setText(railway.getArrival());
        txtRoomAvail.setText(Double.toString(railway.getRoomAvail()));
        comboTime.setSelectedItem(railway.getTime());
        comboSeatType.setSelectedItem(railway.getSeatType());
        comboRoom.setSelectedItem(railway.getRoomType());
        txtSeatAvail.setEditable(false);
     }
    
    private void UpdateRailwayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateRailwayBtnActionPerformed
        // TODO add your handling code here:

        String railwayNum;

        String date;
        String departure;
        String arrival;
        double price;
        double roomAvail;
        if (txtRailWayNum.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Error: You must enter a valid string for Flight Number", "Warning", JOptionPane.INFORMATION_MESSAGE);
            txtRailWayNum.setText("");
            return;
        }
        else{
            railwayNum = txtRailWayNum.getText();
        }

        if (txtDate.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Error: You must enter a valid string for Date!", "Warning", JOptionPane.INFORMATION_MESSAGE);
            txtDate.setText("");
            return;
        }
        else{
            date = txtDate.getText();
        }

        if (txtDeparture.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Error: You must enter a valid string for Departure!", "Warning", JOptionPane.INFORMATION_MESSAGE);
            txtDeparture.setText("");
            return;
        }
        else{
            departure = txtDeparture.getText();
        }

        if (txtArrival.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Error: You must enter a valid string for Arrival!", "Warning", JOptionPane.INFORMATION_MESSAGE);
            txtArrival.setText("");
            return;
        }
        else{
            arrival = txtArrival.getText();
        }

        try{
            price = Double.parseDouble(txtPrice.getText());
        }
        catch(InputMismatchException exception){
            JOptionPane.showMessageDialog(null, "Error: You must enter a double for the Price!", "Warning", JOptionPane.INFORMATION_MESSAGE);
            txtPrice.setText("");
            return;
        }
         try{
            roomAvail = Double.parseDouble(txtRoomAvail.getText());
        }
        catch(InputMismatchException exception){
            JOptionPane.showMessageDialog(null, "Error: You must enter a double for the Available Rooms!", "Warning", JOptionPane.INFORMATION_MESSAGE);
            txtRoomAvail.setText("");
            return;
        }

        //        for (RailWay r : railwayDir.getRailwayDir()){
            //            if (r.getRailwayNum().equals(flightNum)){
                //                JOptionPane.showMessageDialog(null, "Error: This FLight Number already exists, it should be unique! Try again!", "Warning", JOptionPane.INFORMATION_MESSAGE);
                //                txtRailWayNum.setText("");
                //                return;
                //            }
            //        }

 for (RailWay r : useraccount.getRailwayCatalog()){
            if (txtRailWayNum.getText().equals(r.getRailwayNum())){        
//RailWay railway = useraccount.addRailway();
        //railway.setRailwayNum(railwayNum);

        r.setDate(date);
        r.setTime((String)comboTime.getSelectedItem());
        r.setDeparture(departure);
        r.setArrival(arrival);
        r.setSeatAvail(150);
        r.setPrice(price);
        r.setRoomAvail(roomAvail);
        r.setRoomType((String)comboRoom.getSelectedItem());
        r.setSeatType((String)comboSeatType.getSelectedItem());
        JOptionPane.showMessageDialog(null, "RailWay successfully updated", "Warning", JOptionPane.INFORMATION_MESSAGE);
            }
 }
    }//GEN-LAST:event_UpdateRailwayBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        RailWayManageJPanel railwayManagePanel = (RailWayManageJPanel) component;
        railwayManagePanel.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void comboTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTimeActionPerformed

    private void comboSeatTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSeatTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSeatTypeActionPerformed

    private void comboSeatType1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSeatType1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSeatType1ActionPerformed

    private void txtRoomAvailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoomAvailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoomAvailActionPerformed

    private void comboRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboRoomActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UpdateRailwayBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox comboRoom;
    private javax.swing.JComboBox comboSeatType;
    private javax.swing.JComboBox comboSeatType1;
    private javax.swing.JComboBox comboTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtArrival;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDeparture;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtRailWayNum;
    private javax.swing.JTextField txtRoomAvail;
    private javax.swing.JTextField txtSeatAvail;
    // End of variables declaration//GEN-END:variables
}
