/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdministrativeRole;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import Business.EcoSystem;
import Business.Organization.CustomerOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Hotel;
import java.awt.CardLayout;
import javax.swing.JPanel;
import Business.UserAccount.UserAccount;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.*;
import Business.WorkQueue.*;
import Business.WorkQueue.WorkRequest;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.table.DefaultTableModel;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
/**
 *
 * @author Oliver
 */
public class AdminHotelOrderJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminHotelOrderJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount adminUserAccount;
    private CustomerOrganization customerOrganization;
    private Map<String, Double> hotelMap;
    public AdminHotelOrderJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.adminUserAccount = account;
        this.system = business;
        this.customerOrganization = (CustomerOrganization)organization;
        hotelMap = new HashMap<String, Double>();
        populateTable();
    }

    public void populateTable(){
        
        int rowCount = tableOrderHistory.getRowCount();
        DefaultTableModel model = (DefaultTableModel)tableOrderHistory.getModel();
        for(int i=rowCount-1;i>=0;i--) {
            model.removeRow(i);
        }
        //System.out.println(customerOrganization.getUserAccountDirectory().getUserAccountList().size());
        for(UserAccount cusAccount : customerOrganization.getUserAccountDirectory().getUserAccountList()){
            if (cusAccount.getCustomerBooking().size() == 0){
                continue;
            }
            int cnt = 0;
            //System.out.println("Flight orders size: "+cusAccount.getFlightOrder().size());
            for (Hotel h : cusAccount.getCustomerBooking()){
                Object row[] = new Object[8];
                row[0] = cusAccount.getEmail();
                row[1] = cusAccount.getCustomerBooking().get(cnt).getName();
                row[2] = cusAccount.getCustomerBooking().get(cnt).getStars();
                row[3] = cusAccount.getCustomerBooking().get(cnt).getRoomtype();
                row[4] = cusAccount.getCustomerBooking().get(cnt).getParking();
                row[5] = cusAccount.getCustomerBooking().get(cnt).getWifi();
                if (cusAccount.getWorkQueue().getRequestMap().get("Hotel").get(cnt).getPriceChange()){
                    row[6] = cusAccount.getWorkQueue().getRequestMap().get("Hotel").get(cnt).getPrice();
                }
                else{
                    row[6] = h.getPrice();
                }
                model.addRow(row);
                cnt++;
            }
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableOrderHistory = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        btnAnalyzeRailway = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("HOTEL ORDER HISTORY");

        tableOrderHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Customer Email", "Hotel Name", "Stars", "Room Type", "Parking", "Wifi", "Price"
            }
        ));
        jScrollPane1.setViewportView(tableOrderHistory);

        backBtn.setText("<<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        btnAnalyzeRailway.setText("Analyze Hotel");
        btnAnalyzeRailway.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalyzeRailwayActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/AdministrativeRole/icon-p_lishibaobiao.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/AdministrativeRole/zonghefenxi.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/AdministrativeRole/denglu.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/AdministrativeRole/riqi.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/AdministrativeRole/jiudian.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/AdministrativeRole/wifi.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(432, 432, 432)
                        .addComponent(jLabel2)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(backBtn)
                        .addGap(665, 665, 665)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(btnAnalyzeRailway))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 912, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel6)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel7))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(backBtn)
                        .addComponent(btnAnalyzeRailway))
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void btnAnalyzeRailwayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalyzeRailwayActionPerformed
        // TODO add your handling code here:
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        for(UserAccount cusAccount : customerOrganization.getUserAccountDirectory().getUserAccountList()){
            if (cusAccount.getCustomerBooking().size() == 0){
                continue;
            }
            for (Hotel h : cusAccount.getCustomerBooking()){
                if (hotelMap.containsKey(h.getName())){

                    hotelMap.put(h.getName(), hotelMap.get(h.getName())+h.getPrice());
                }
                else{

                    hotelMap.put(h.getName(), h.getPrice());

                }
            }
        }
        Set<Map.Entry<String, Double>> set = hotelMap.entrySet();
        List<Map.Entry<String, Double>> list = new ArrayList<Map.Entry<String, Double>>(set);
        Collections.sort( list, new Comparator<Map.Entry<String, Double>>()
            {
                public int compare( Map.Entry<String, Double> o1, Map.Entry<String, Double> o2 )
                {
                    return (o2.getValue()).compareTo( o1.getValue() );
                }
            } );
            for(Map.Entry<String, Double> entry:list){
                dataset.setValue(entry.getValue(), "Sales Value($)", entry.getKey());
            }
            JFreeChart hotelChart = ChartFactory.createBarChart("Hotel Total Sales Value", "Hotel Name", "Sales Value($)", dataset, PlotOrientation.VERTICAL, false, true, false);
            CategoryPlot p = hotelChart.getCategoryPlot();
            p.setRangeGridlinePaint(Color.BLACK);
            ChartFrame frame = new ChartFrame("Bar chart for railways", hotelChart);
            frame.setVisible(true);
            frame.setSize(800, 500);
    }//GEN-LAST:event_btnAnalyzeRailwayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton btnAnalyzeRailway;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableOrderHistory;
    // End of variables declaration//GEN-END:variables
}
