/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdministrativeRole;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import Business.EcoSystem;
import Business.Organization.CustomerOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.RailWay;
import java.awt.CardLayout;
import javax.swing.JPanel;
import Business.UserAccount.UserAccount;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.*;
import Business.WorkQueue.*;
import Business.WorkQueue.WorkRequest;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.table.DefaultTableModel;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
/**
 *
 * @author Oliver
 */
public class AdminRailwayOrderJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminRailwayOrderJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount adminUserAccount;
    private CustomerOrganization customerOrganization;
    private Map<String, Double> railwayMap;
    public AdminRailwayOrderJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.adminUserAccount = account;
        this.system = business;
        this.customerOrganization = (CustomerOrganization)organization;
        railwayMap = new HashMap<String, Double>();
        populateTable();
    }

    public void populateTable(){
        
        int rowCount = tableOrderHistory.getRowCount();
        DefaultTableModel model = (DefaultTableModel)tableOrderHistory.getModel();
        for(int i=rowCount-1;i>=0;i--) {
            model.removeRow(i);
        }
        //System.out.println(customerOrganization.getUserAccountDirectory().getUserAccountList().size());
        for(UserAccount cusAccount : customerOrganization.getUserAccountDirectory().getUserAccountList()){
            if (cusAccount.getCustomerRailWayBooking().size() == 0){
                continue;
            }
            int cnt = 0;
            //System.out.println("Flight orders size: "+cusAccount.getFlightOrder().size());
            for (RailWay r : cusAccount.getCustomerRailWayBooking()){
                Object row[] = new Object[8];
                row[0] = cusAccount.getEmail();
                row[1] = cusAccount.getCustomerRailWayBooking().get(cnt).getCompanyName();
                row[2] = cusAccount.getCustomerRailWayBooking().get(cnt).getRailwayNum();
                row[3] = cusAccount.getCustomerRailWayBooking().get(cnt).getDate();
                row[4] = cusAccount.getCustomerRailWayBooking().get(cnt).getDeparture();
                row[5] = cusAccount.getCustomerRailWayBooking().get(cnt).getArrival();
                row[6] = cusAccount.getCustomerRailWayBooking().get(cnt).getSeatType();
                if (cusAccount.getWorkQueue().getRequestMap().get("RailWay").get(cnt).getPriceChange()){
                    row[7] = cusAccount.getWorkQueue().getRequestMap().get("RailWay").get(cnt).getPrice();
                }
                else{
                    row[7] = r.getPrice();
                }
                model.addRow(row);
                cnt++;
            }
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableOrderHistory = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        btnAnalyzeRailway = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        tableOrderHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Customer Email", "Railway Company", "Train Number", "Date", "Departure", "Arrival", "Seat Type", "Price"
            }
        ));
        jScrollPane1.setViewportView(tableOrderHistory);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("RAILWAY TRAIN ORDER HISTORY");

        backBtn.setText("<<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        btnAnalyzeRailway.setText("Analyze Railways");
        btnAnalyzeRailway.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalyzeRailwayActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/AdministrativeRole/icon-p_lishibaobiao.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/AdministrativeRole/zonghefenxi.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/AdministrativeRole/denglu.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/AdministrativeRole/riqi.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/AdministrativeRole/tielu.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/AdministrativeRole/zuowei.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(331, 331, 331)
                                .addComponent(jLabel2)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(backBtn)
                                .addGap(624, 624, 624)
                                .addComponent(jLabel3)
                                .addGap(31, 31, 31)
                                .addComponent(btnAnalyzeRailway)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 933, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(backBtn)
                                .addComponent(btnAnalyzeRailway))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel6)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void btnAnalyzeRailwayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalyzeRailwayActionPerformed
        // TODO add your handling code here:
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        for(UserAccount cusAccount : customerOrganization.getUserAccountDirectory().getUserAccountList()){
            if (cusAccount.getCustomerRailWayBooking().size() == 0){
                continue;
            }
            for (RailWay r : cusAccount.getCustomerRailWayBooking()){
                if (railwayMap.containsKey(r.getCompanyName())){

                    railwayMap.put(r.getCompanyName(), railwayMap.get(r.getCompanyName())+r.getPrice());
                }
                else{

                    railwayMap.put(r.getCompanyName(), r.getPrice());

                }
            }
        }
        Set<Map.Entry<String, Double>> set = railwayMap.entrySet();
        List<Map.Entry<String, Double>> list = new ArrayList<Map.Entry<String, Double>>(set);
        Collections.sort( list, new Comparator<Map.Entry<String, Double>>()
            {
                public int compare( Map.Entry<String, Double> o1, Map.Entry<String, Double> o2 )
                {
                    return (o2.getValue()).compareTo( o1.getValue() );
                }
            } );
            for(Map.Entry<String, Double> entry:list){
                dataset.setValue(entry.getValue(), "Sales Value($)", entry.getKey());
            }
            JFreeChart railwayChart = ChartFactory.createBarChart("Railway Total Sales Value", "Railway Name", "Sales Value($)", dataset, PlotOrientation.VERTICAL, false, true, false);
            CategoryPlot p = railwayChart.getCategoryPlot();
            p.setRangeGridlinePaint(Color.BLACK);
            ChartFrame frame = new ChartFrame("Bar chart for railways", railwayChart);
            frame.setVisible(true);
            frame.setSize(800, 500);
    }//GEN-LAST:event_btnAnalyzeRailwayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton btnAnalyzeRailway;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableOrderHistory;
    // End of variables declaration//GEN-END:variables
}
