/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Hotel;

import Business.Hotel;
import Business.WorkQueue.HotelWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author chenweikai
 */
public class ApproveHotelBookingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ApproveHotelBookingJPanel
     */
    JPanel userProcessContainer;
    HotelWorkRequest request;
    Hotel myHotel;
    public ApproveHotelBookingJPanel(JPanel userProcessContainer, HotelWorkRequest request, Hotel myHotel) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.myHotel = myHotel;
        if (request.getIsCancellation()){
            labelIsCancel.setText("Yes");
        }
        else{
            labelIsCancel.setText("No");
        }
        if (request.getIsCredits()){
            labelIsCredits.setText("Yes");
            //labelOriginalPrice.setText(Double.toString(request.getSender().getCustomerBooking().get(request.getRow()).getPrice()));
            btnGenNewPrice.setEnabled(true);
        }
        else{
            btnGenNewPrice.setEnabled(false);
            labelIsCredits.setText("No");
        }
        
        labelCredits.setText(Double.toString(request.getSender().getCredits()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDeclineRoom = new javax.swing.JButton();
        btnApproveRoom = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnGenNewPrice = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        labelCredits = new javax.swing.JLabel();
        labelIsCredits = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelIsCancel = new javax.swing.JLabel();
        txtDeclineMsg = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        labelNewPrice = new javax.swing.JLabel();
        comboAddBed = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        comboMeetingRoomtype = new javax.swing.JComboBox();
        labelIsCancel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtDeclineMsg1 = new javax.swing.JTextField();
        btnApproveMeetingRoom = new javax.swing.JButton();
        btnDeclineMeetingRoom = new javax.swing.JButton();

        btnDeclineRoom.setText("Decline Room request");
        btnDeclineRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeclineRoomActionPerformed(evt);
            }
        });

        btnApproveRoom.setText("Approve Room request");
        btnApproveRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveRoomActionPerformed(evt);
            }
        });

        backJButton.setText("<<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Approve Room Request"));

        jLabel4.setText("New Price: ");

        btnGenNewPrice.setText("Generate New Price");
        btnGenNewPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenNewPriceActionPerformed(evt);
            }
        });

        jLabel10.setText("Customer's Credits: ");

        labelCredits.setText("Display Credits");

        labelIsCredits.setText("Yes/No");

        jLabel12.setText("Using credits?");

        jLabel6.setText("A cancellation request?");

        labelIsCancel.setText("Yes/No");

        txtDeclineMsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeclineMsgActionPerformed(evt);
            }
        });

        jLabel5.setText("Decline reason");

        comboAddBed.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2"}));
        comboAddBed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAddBedActionPerformed(evt);
            }
        });

        jLabel13.setText("Add beds");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(btnGenNewPrice)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelIsCancel)
                        .addGap(85, 85, 85))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                                .addComponent(txtDeclineMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12))
                                .addGap(54, 54, 54)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCredits, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(comboAddBed, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelIsCredits))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addContainerGap(13, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelNewPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(labelIsCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(labelCredits))
                .addGap(18, 18, 18)
                .addComponent(btnGenNewPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(comboAddBed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelNewPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIsCancel)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDeclineMsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Approve Meeting Room Request"));

        jLabel7.setText("A Cancellation Request:");

        comboMeetingRoomtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Small", "Medium", "Large"}));
        comboMeetingRoomtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMeetingRoomtypeActionPerformed(evt);
            }
        });

        labelIsCancel1.setText("Yes/No");

        jLabel9.setText("Change Meeting Room Type");

        jLabel11.setText("Decline reason");

        txtDeclineMsg1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeclineMsg1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(labelIsCancel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDeclineMsg1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboMeetingRoomtype, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(comboMeetingRoomtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDeclineMsg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(labelIsCancel1))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        btnApproveMeetingRoom.setText("Approve Meeting Room request");
        btnApproveMeetingRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveMeetingRoomActionPerformed(evt);
            }
        });

        btnDeclineMeetingRoom.setText("Decline Meeting Room request");
        btnDeclineMeetingRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeclineMeetingRoomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backJButton)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnApproveMeetingRoom)
                            .addComponent(btnDeclineMeetingRoom))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDeclineRoom)
                            .addComponent(btnApproveRoom))
                        .addGap(37, 37, 37))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backJButton)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(btnApproveRoom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeclineRoom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnApproveMeetingRoom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeclineMeetingRoom)
                .addGap(183, 183, 183))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeclineRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeclineRoomActionPerformed
        // TODO add your handling code here:
        
       
        
        
         if (txtDeclineMsg.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please return an explanation for declined request!", "Warning", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (request.getIsCancellation()){
            request.getSender().getWorkQueue().getRequestMap().get("Hotel").get(request.getRow()).setStatus("Cancellation Declined");
            request.setStatus("Completed");
            
            double m = request.getSender().getCustomerBooking().get(request.getRow()).getRoomnumbers() + 1;
            request.getSender().getCustomerBooking().get(request.getRow()).setRoomnumbers(m);
            request.getSender().getWorkQueue().getRequestMap().get("Hotel").get(request.getRow()).setMessage(txtDeclineMsg.getText());
        }
        else{
            //if rent being declined, there's no such order in customerBooking
            request.setStatus("Declined");
            
            for (Hotel hotel : request.getReceiver().getHotelCatalog()){
                if (hotel.getHotelid()==(myHotel.getHotelid())){
                    hotel.setIsAvailable(true);
                    double m =hotel.getRoomnumbers() + 1;
                    hotel.setRoomnumbers(m);
                }
            }
            int cnt = 0;
            for (Hotel hotel : request.getSender().getCustomerBooking()){
                if ((hotel.getName().equals(myHotel.getName()))&&(hotel.getHotelid()==myHotel.getHotelid())){
                    break;
                }
                cnt++;
            }
            request.getSender().getCustomerBooking().remove(cnt);
            request.getSender().getWorkQueue().getRequestMap().get("Hotel").remove(cnt);
            
        }
        System.out.println("OrderHistory: order size: " + request.getSender().getCustomerBooking().size() + ", Hotel request size" + request.getSender().getWorkQueue().getRequestMap().get("Hotel").size());
        request.setMessage(txtDeclineMsg.getText());
        
        JOptionPane.showMessageDialog(null, "Action has been done to this request!", "Warning", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnDeclineRoomActionPerformed

    private void btnApproveRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveRoomActionPerformed
       String newPrice = "";
        if (request.getIsCancellation()){
            
            request.getSender().getCustomerBooking().get(request.getRow()).setIsAvailable(true);
            System.out.println("approve panel: " + request.getPrice());
            if (request.getSender().getCredits()-request.getPrice()/10.0 >= 0.0){
                request.getSender().addCredits(0-request.getPrice()/10.0);
            }
            request.getSender().getCustomerBooking().remove(request.getRow());
            //System.out.println("???????  " + request.getRow());
            //System.out.println("before: " + request.getSender().getWorkQueue().getWorkRequestList().size());
            //request.getSender().getWorkQueue().getWorkRequestList().remove(request.getSender().getWorkQueue().getWorkRequestList().size()-1);
            request.getSender().getWorkQueue().getRequestMap().get("Hotel").remove(request.getRow());
            System.out.println("Approve panel: orderhistory" + request.getSender().getCustomerBooking().size() + ", request row: " + request.getRow());
            
            //System.out.println("after: " + request.getSender().getWorkQueue().getWorkRequestList().size());
        }
        //        else if ((String)comboClass.getSelectedItem()!="" && txtNewPrice.getText() != ""){
            //            request.setNewClass((String)comboClass.getSelectedItem());
            //            request.setNewPrice(Double.parseDouble(txtNewPrice.getText()));
            //
            //        }

        else{
            
            
            if (request.getIsCredits()){
                System.out.println(labelNewPrice.getText());
                if (labelNewPrice.getText().trim().equals("")){
                    JOptionPane.showMessageDialog(null, "Please check the new price with customer credits included!", "Warning", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
                for (Hotel hotel : request.getReceiver().getHotelCatalog()){
                    if (hotel.getHotelid()==(myHotel.getHotelid())){
                        hotel.setIsAvailable(false);
                    }
                }
                request.getSender().addCredits(Double.parseDouble(labelNewPrice.getText())/10.0);
                request.setPriceChange(true);
                request.setPrice(Double.parseDouble(labelNewPrice.getText()));
                
            }
            else{
                request.getSender().addCredits(myHotel.getPrice()/10.0);
                for (Hotel hotel : request.getReceiver().getHotelCatalog()){
                    if (hotel.getHotelid()==(myHotel.getHotelid())){
                        hotel.setIsAvailable(false);
                    }
                }
            }
            
            //System.out.println(request.getSender().getCustomerBooking().get(request.getRow()).getIsAvailable());
        }
        
        request.setStatus("Completed");
        request.setMessage("Request approved");
        JOptionPane.showMessageDialog(null, "Action has been done to this request!", "Warning", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnApproveRoomActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        HotelWorkAreaJPanel hotelWorkAreaJP = (HotelWorkAreaJPanel) component;
        hotelWorkAreaJP.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void comboMeetingRoomtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMeetingRoomtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboMeetingRoomtypeActionPerformed

    private void txtDeclineMsg1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeclineMsg1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeclineMsg1ActionPerformed

    private void btnApproveMeetingRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveMeetingRoomActionPerformed
        // TODO add your handling code here:
        
        if (request.getIsCancellation()){
            request.getSender().getCustomerBooking().get(request.getRow()).setIsAvailable(true);
            request.getSender().getCustomerBooking().remove(request.getRow());
            //System.out.println("???????  " + request.getRow());
            //System.out.println("before: " + request.getSender().getWorkQueue().getWorkRequestList().size());
            //request.getSender().getWorkQueue().getWorkRequestList().remove(request.getSender().getWorkQueue().getWorkRequestList().size()-1);
            request.getSender().getWorkQueue().getWorkRequestList().remove(request.getRow());

            //System.out.println("after: " + request.getSender().getWorkQueue().getWorkRequestList().size());
        }
        //        else if ((String)comboClass.getSelectedItem()!="" && txtNewPrice.getText() != ""){
            //            request.setNewClass((String)comboClass.getSelectedItem());
            //            request.setNewPrice(Double.parseDouble(txtNewPrice.getText()));
            //
            //        }

        else{
            if ((String)comboMeetingRoomtype.getSelectedItem()!=""){
                request.setNewClass((String)comboMeetingRoomtype.getSelectedItem());

            };
            
           
            request.getSender().getCustomerBooking().get(request.getRow()).setIsAvailable(false);
        }

        request.setStatus("Completed");
        request.setMessage("Request approved");
        JOptionPane.showMessageDialog(null, "Action has been done to this request!", "Warning", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnApproveMeetingRoomActionPerformed

    private void btnDeclineMeetingRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeclineMeetingRoomActionPerformed
        // TODO add your handling code here:
        
         double m = request.getSender().getCustomerBooking().get(request.getRow()).getMeetingroomnumbers() + 1;
        request.getSender().getCustomerBooking().get(request.getRow()).setMeetingroomnumbers(m);
        
        
        if (txtDeclineMsg.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please return an explanation for declined request!", "Warning", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (request.getIsCancellation()){
            request.setStatus("Completed");
            request.getSender().getCustomerBooking().get(request.getRow()).setIsAvailable(false);
        }
        else{
            //if rent being declined, there's no such order in customerOrder
            request.setStatus("Declined");
            request.getSender().getCustomerBooking().get(request.getRow()).setIsAvailable(true);
            request.getSender().getCustomerBooking().remove(request.getRow());
            request.getSender().getWorkQueue().getWorkRequestList().remove(request.getRow());

        }

        request.setMessage(txtDeclineMsg.getText());
        JOptionPane.showMessageDialog(null, "Action has been done to this request!", "Warning", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnDeclineMeetingRoomActionPerformed

    private void btnGenNewPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenNewPriceActionPerformed
        // TODO add your handling code here:

        
        String addbeds = (String)comboAddBed.getSelectedItem();
        if(addbeds =="0"){
             Double newPrice = myHotel.getPrice() - Double.parseDouble(labelCredits.getText());
             labelNewPrice.setText(Double.toString(newPrice));
        }
        if(addbeds =="1"){
             Double newPrice = myHotel.getPrice() - Double.parseDouble(labelCredits.getText()) + 20;
             labelNewPrice.setText(Double.toString(newPrice));
        }
        if(addbeds =="2"){
             Double newPrice = myHotel.getPrice() - Double.parseDouble(labelCredits.getText()) + 40;
             labelNewPrice.setText(Double.toString(newPrice));
        }

    }//GEN-LAST:event_btnGenNewPriceActionPerformed

    private void txtDeclineMsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeclineMsgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeclineMsgActionPerformed

    private void comboAddBedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAddBedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAddBedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnApproveMeetingRoom;
    private javax.swing.JButton btnApproveRoom;
    private javax.swing.JButton btnDeclineMeetingRoom;
    private javax.swing.JButton btnDeclineRoom;
    private javax.swing.JButton btnGenNewPrice;
    private javax.swing.JComboBox comboAddBed;
    private javax.swing.JComboBox comboMeetingRoomtype;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelCredits;
    private javax.swing.JLabel labelIsCancel;
    private javax.swing.JLabel labelIsCancel1;
    private javax.swing.JLabel labelIsCredits;
    private javax.swing.JLabel labelNewPrice;
    private javax.swing.JTextField txtDeclineMsg;
    private javax.swing.JTextField txtDeclineMsg1;
    // End of variables declaration//GEN-END:variables
}
