/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Customer;
import Business.Airliner;
import Business.EcoSystem;
import Business.Organization.CustomerOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.AirlinerDirectory;
import Business.Car;
import java.awt.CardLayout;
import javax.swing.JPanel;
import Business.UserAccount.UserAccount;
import Business.Enterprise.Enterprise;
import Business.Flight;
import Business.Network.Network;
import Business.Organization.*;
import javax.swing.JOptionPane;
import java.util.ArrayList;
/**
 *
 * @author Oliver
 */
public class CustomerAirFlightJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerAirFlightJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount userAccount;
    private CustomerOrganization customerOrganization;
    public CustomerAirFlightJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.system = business;
        this.customerOrganization = (CustomerOrganization)organization;
        comboFlightNum.removeAllItems();
        comboDeparture.removeAllItems();
        comboArrival.removeAllItems();
        comboDate.removeAllItems();
        comboTime.removeAllItems();
        
        comboFlightNum.addItem("");
        comboDeparture.addItem("");
        comboArrival.addItem("");
        comboDate.addItem("");
        comboTime.addItem("");
        ArrayList<Object> tempDep = new ArrayList<Object>();
        ArrayList<Object> tempArr = new ArrayList<Object>();
        ArrayList<Object> tempDate = new ArrayList<Object>();
        ArrayList<Object> tempTime = new ArrayList<Object>();
        for (Network network : this.system.getNetworkList()){
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
                if (enterprise.getName().equals(customerOrganization.getEnterpriseName())){
                    //System.out.println(enterprise.getName());
                    for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()){
                        if (org.getName().equals("Airliner Organization")){
                            for (UserAccount useraccount : org.getUserAccountDirectory().getUserAccountList()){
                                for (Flight flight : useraccount.getFlightCatalog()){
                                    comboFlightNum.addItem(flight.getFlightNum());
                                    if (!tempDep.contains(flight.getDeparture())){
                                        comboDeparture.addItem(flight.getDeparture());
                                        tempDep.add(flight.getDeparture());
                                    }
                                    if (!tempArr.contains(flight.getArrival())){
                                        comboArrival.addItem(flight.getArrival());
                                        tempArr.add(flight.getArrival());
                                    }
                                    if (!tempDate.contains(flight.getDate())){
                                        comboDate.addItem(flight.getDate());
                                        tempDate.add(flight.getDate());
                                    }
                                    if (tempTime.contains(flight.getTime())){
                                        comboTime.addItem(flight.getTime());
                                        tempTime.add(flight.getTime());
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        btnContinue = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnFlightOrders = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboFlightNum = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        comboDeparture = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        comboArrival = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        comboTime = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        comboDate = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        backBtn.setText("<<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        btnContinue.setText("Continue >>>");
        btnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Air-travel History"));

        btnFlightOrders.setText("My Orders");
        btnFlightOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlightOrdersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnFlightOrders)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnFlightOrders)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel6.setText("BOOK A FLIGHT!");

        jLabel3.setText("Flight Number");

        comboFlightNum.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Departure");

        comboDeparture.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Arrival");

        comboArrival.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Preferred Time of Day");

        comboTime.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Date");

        comboDate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Airliner/feiji.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/AdministrativeRole/shuzi.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Airliner/-departure-.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Airliner/-landing.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/AdministrativeRole/shijian.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/AdministrativeRole/riqi.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Airliner/chakan.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(backBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))
                            .addComponent(jLabel8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnContinue)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel11)
                                                .addComponent(jLabel10))
                                            .addGap(51, 51, 51))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel12)
                                                .addComponent(jLabel9))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel3))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addGap(113, 113, 113)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(comboFlightNum, 0, 131, Short.MAX_VALUE)
                                        .addComponent(comboArrival, 0, 131, Short.MAX_VALUE)
                                        .addComponent(comboDeparture, 0, 131, Short.MAX_VALUE)
                                        .addComponent(comboTime, 0, 131, Short.MAX_VALUE)
                                        .addComponent(comboDate, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel13)
                        .addGap(33, 33, 33)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel6)))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(comboFlightNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(comboDeparture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboArrival, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(comboTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(comboDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(btnContinue))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel13)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed
        // TODO add your handling code here:
        String flightNum = (String)comboFlightNum.getSelectedItem();
        String departure = (String)comboDeparture.getSelectedItem();
        String arrival = (String)comboArrival.getSelectedItem();
        String time = (String)comboTime.getSelectedItem();
        String date = (String)comboDate.getSelectedItem();
        if (searchAir(flightNum, departure, arrival, time, date) == null){
            JOptionPane.showMessageDialog(null, "No available Car found:( Search again!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        ArrayList<Flight> flightList = new ArrayList<Flight>();
        flightList = searchAir(flightNum, departure, arrival, time, date);
        CustomerFlightResultJPanel cusCarSearchResJP = new CustomerFlightResultJPanel(userProcessContainer, userAccount, customerOrganization, system, flightList);
        userProcessContainer.add("CustomerCarSearchResultJPanel",cusCarSearchResJP);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnContinueActionPerformed

    private ArrayList<Flight> searchAir(String flightNum, String departure, String arrival, String time, String date){
        ArrayList<Flight> flightList = new ArrayList<Flight>();
        int cnt = 0;
        for (Network network : system.getNetworkList()){
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
                //System.out.println("Customer's enterprise: " + customerOrganization.getEnterpriseName() + ", Enterprise in directory: " + enterprise.getEnterpriseName());
                if (enterprise.getName().equals(customerOrganization.getEnterpriseName())){
                   for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()){
                        if (org.getName().equals("Airliner Organization")){
                            for (UserAccount useraccount : org.getUserAccountDirectory().getUserAccountList()){
                                for (Flight f : useraccount.getFlightCatalog()){
                                    if ((!flightNum.equals("")) && (f.getFlightNum().equals(flightNum) == false)){
                                        continue;
                                    }
                                    if ((!departure.equals("")) && (f.getDeparture().equals(departure)==false)){
                                        continue;
                                    }
                                    if ((!arrival.equals("")) && (f.getArrival().equals(arrival)==false)){
                                        continue;
                                    }
                                    if ((!time.equals("")) && (f.getTime().equals(time)==false)){
                                        continue;
                                    }
                                    if ((!date.equals("")) && (f.getDate().equals(date)==false)){
                                        continue;
                                    }
                                    flightList.add(f);
                                    cnt++;
                                }
                            }
                        }
                    } 
                }
                
            }
        }
        if (cnt == 0){
            return null;
        }
        return flightList;
    }
    
    private void btnFlightOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlightOrdersActionPerformed
        // TODO add your handling code here:
        CustomerAirFlightHistoryJPanel customerFlightHistoryJP=new CustomerAirFlightHistoryJPanel(userProcessContainer, userAccount, customerOrganization, system);
        userProcessContainer.add("CustomerAirFlightHistoryJPanel",customerFlightHistoryJP);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnFlightOrdersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton btnContinue;
    private javax.swing.JButton btnFlightOrders;
    private javax.swing.JComboBox comboArrival;
    private javax.swing.JComboBox comboDate;
    private javax.swing.JComboBox comboDeparture;
    private javax.swing.JComboBox comboFlightNum;
    private javax.swing.JComboBox comboTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
